# Generated by Django 6.0.3 on 2026-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='Default.jpg', upload_to='uploads/'),
        ),
    ]
