# Generated by Django 6.0.3 on 2026-03-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_taskmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='profile',
            field=models.ImageField(default='Default.jpg', upload_to='uploads'),
        ),
    ]
