# Generated by Django 6.0.3 on 2026-03-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_taskmodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='profile',
        ),
    ]
